### ISSUE TITLE
Plugin is changing birthdays in contact database

### ISSUE THREAD

**Issue by bikelanta** [motschel123/Mac-Contact-Sync-Obsidian#7] opened 2023-12-20 17:01 UTC
The plugin is advancing birthdays for my contacts. As in, if it was 1/1 originally in the contact database, it is being changed to 1/2.

**Comment by bikelanta** [comment] 2023-12-20 23:09
So the behavior is strange. After invoking the plugin, the following happens
1. If the contact is in iCloud, the birthdate in iCloud does not change, but is synced to Obsidian as one day earlier. So if the birthday is 1/1/2023 it gets put into Obsidian as 12/31/2022
2. If the contact is in Exchange, the birthdate in Exchange increments up one day and the birthdate put into Obsidian is one day earlier. So a 1/1/2023 birthday in Exchange becomes 12/31/2022 in Obsidian and 1/2/23 in Exchange

**Comment by motschel123** [comment] 2023-12-22 15:34
Thanks for the feedback.

I checked with a dummy contact and could not reproduce the error. 
Please create a dummy contact, export the vcard and add it to this issue so I can reproduce the issue and fix it.

**Comment by bikelanta** [comment] 2024-01-09 16:37
Here are three dummy vCards. I put in the notes where they were created. 2 are created in an Exchange account. 1 was created in an iCloud account. They all have birthdays on the 14th of the noted month. With the Exchange contacts, they both sync into Obsidian with correct birthdays. The iCloud contact syncs with a birthday on the 13th.

[vCards.zip](https://github.com/motschel123/Mac-Contact-Sync-Obsidian/files/13876444/vCards.zip)

**Comment by motschel123** [comment] 2024-01-10 13:04
Thanks for the informations.

Can you let me know which country settings you have set on your machine, there might be an issue with date parsing on machines set to US or other English countries.

**Comment by bikelanta** [comment] 2024-01-10 16:53
The Mac itself is set to United States as the region with the Gregorian calendar.

**Comment by motschel123** [comment] 2024-04-22 10:11
Sorry for taking so long to come back to you.
I tried to reproduce the error by setting my region to US and loading your provided vCards, but I had no issues with the dates. 
I'm sorry if the error still persists on your side, but without reproducing it, I won't be able to fix it and will close this issue.

**Closed by motschel123** 2024-04-22 10:11 UTC
Labels: bug, question
